general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font" }
bold = { family = "CaskaydiaMono Nerd Font" }
italic = { family = "CaskaydiaMono Nerd Font" }
size = 14

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" },
  { key = "Return", mods = "Shift", chars = "\u001B\r" },
  { key = "S", mods = "Control|Shift", chars = "As a I want to so that I can\n\nAcceptance Criteria:\n\nTesting Plan:\n\nDeveloper Notes:" },
  { key = "E", mods = "Control|Shift", chars = "user@example.com" }
]

[terminal]
osc52 = "CopyPaste"

[terminal.shell]
program = "/usr/bin/bash"
args = ["--login"]
